export enum PagePaths {
    Home = "/",
    Dashboard = "/dashboard",
    Faq = "/frequently-asked-questions",
    ShoppingCart = "/shopping-cart",
    TwitchViewer = "/viewbotting-on-twitch-service",
    TrovoViewer = "/trovo-viewer-bot-plans",
    KickViewer = "/kick-viewer-bot",
    YoutubeViewer = "/youtube-viewer-bot",
    TwitchFollower = "/twitch-follower",
    Login = "/login",
    Register = "/register",
    Order = "/orders",
    Signout = "/api/auth/signout",
    ForgotPassword = "/forgot-password",
    AboutUs = "#",
    ContactUs = "/contact-us",
    TermsOfUse = "#",
    KnowledgeBase = "/knowledge-base",
    Memberships = "/memberships",
    Followers = "/followers-bot",
    Checkout = "/checkout",

}